// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3N3KfT8fGfeUOLGGv51cz7GGHT2l8RI',
    appId: '1:713454357946:android:f182d7df5b2a500b29a183',
    messagingSenderId: '713454357946',
    projectId: 'quietpass-app',
    storageBucket: 'quietpass-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugpjyPJoU_ZA5hh6ANUT8nSn43Jqol-0',
    appId: '1:713454357946:ios:e29bc3aa52c031ae29a183',
    messagingSenderId: '713454357946',
    projectId: 'quietpass-app',
    storageBucket: 'quietpass-app.firebasestorage.app',
    iosBundleId: 'com.quietpass.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_jUeujXElmECRrC2FJxi2pGlR1oOyUg',
    appId: '1:713454357946:web:d447812f5dadab4729a183',
    messagingSenderId: '713454357946',
    projectId: 'quietpass-app',
    authDomain: 'quietpass-app.firebaseapp.com',
    storageBucket: 'quietpass-app.firebasestorage.app',
    measurementId: 'G-H5QLX6QMNN',
  );
}
